server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: checkout
---
spring:
  profiles: dev
  data:
    mongodb: 
      host: localhost:27101
      database: checkout
bill-service:
  create: http://localhost:8082/bill/create
  cancel: http://localhost:8082/bill/cancel/{billId}
    
logistic-service:
  create: http://localhost:8083/logistic/create
---
spring:
  profiles: prod
  data:
    mongodb: 
      host: mongodb-checkout:27017
      database: checkout
bill-service:
  create: http://bill-service:8082/bill/create
  cancel: http://bill-service:8082/bill/cancel/{billId}
    
logistic-service:
  create: http://logistic-service:8083/logistic/create